### ISSUE TITLE
WSI task

### ISSUE THREAD

**Issue by kuan-yu-lin** [ChangeIsKey/LSCDBenchmark#33]
Here is the command lines:
```sh
python main.py -m \
    evaluation=none \
    task=wsi \
    task/wsi@task.model=cluster_correlation \
    task/wic@task.model.wic=contextual_embedder \
    task/wic/metric@task.model.wic.similarity_metric=cosine \
    dataset=dwug_de_210 \
    dataset/split=dev \
    dataset/spelling_normalization=english \
    dataset/preprocessing=raw \
    task.model.wic.ckpt=bert-base-german-cased \
    task.model.wic.gpu=1
```
Here is the error:
```
Traceback (most recent call last):
  File "/mount/arbeitsdaten20/projekte/cik/users/kuan-yu/LSCDBenchmark/src/wsi/model.py", line 35, in similarity_matrix
    similarity_matrix[i, j] = pairs_to_similarities[(use_1, use_2)]
KeyError: (Use(identifier='2532889X_1946-10-18_01_059.tcf.xml-2-15', grouping='2', context='Mit geheimnisvoller Miene flüsterten die von Michael Bohnen Entsandten jedem zu, daß heute eine Sensation zu erwarten sei.', target='Sensation', indices=(96, 105), pos='NN'), Use(identifier='2532889X_1946-10-18_01_059.tcf.xml-2-15', grouping='2', context='Mit geheimnisvoller Miene flüsterten die von Michael Bohnen Entsandten jedem zu, daß heute eine Sensation zu erwarten sei.', target='Sensation', indices=(96, 105), pos='NN'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mount/arbeitsdaten20/projekte/cik/users/kuan-yu/LSCDBenchmark/main.py", line 12, in main
    return run(*instantiate(config))
  File "/mount/arbeitsdaten20/projekte/cik/users/kuan-yu/LSCDBenchmark/src/utils/runner.py", line 121, in run
    predictions.update(dict(zip(ids, model.predict(uses))))
  File "/mount/arbeitsdaten20/projekte/cik/users/kuan-yu/LSCDBenchmark/src/wsi/correlation_clustering.py", line 22, in predict
    similarity_matrix = self.similarity_matrix(use_pairs)
  File "/mount/arbeitsdaten20/projekte/cik/users/kuan-yu/LSCDBenchmark/src/wsi/model.py", line 37, in similarity_matrix
    similarity_matrix[i, j] = pairs_to_similarities[(use_2, use_1)]
KeyError: (Use(identifier='2532889X_1946-10-18_01_059.tcf.xml-2-15', grouping='2', context='Mit geheimnisvoller Miene flüsterten die von Michael Bohnen Entsandten jedem zu, daß heute eine Sensation zu erwarten sei.', target='Sensation', indices=(96, 105), pos='NN'), Use(identifier='2532889X_1946-10-18_01_059.tcf.xml-2-15', grouping='2', context='Mit geheimnisvoller Miene flüsterten die von Michael Bohnen Entsandten jedem zu, daß heute eine Sensation zu erwarten sei.', target='Sensation', indices=(96, 105), pos='NN'))
```

**Comment by sachinn12** [comment]
WSI is planned for 2026.

**Comment by sachinn12** [comment]
This issue has been resolved and described in details here #34. Commit: https://github.com/ChangeIsKey/LSCDBenchmark/commit/63452b2618aa7db61647089313c15c7334229f19
