### ISSUE TITLE
Assign value for Callable

### ISSUE THREAD

**Issue by kuan-yu-lin** [ChangeIsKey/LSCDBenchmark#43]
In the plot.py, the metric variable is set for a Callable.
When the Plotter is initiated in the following way, all the function (except for metric_boot_histogram) pass the unit test.
``` python
P = Plotter(max_alpha= 0.5,
            default_alpha=0.3, 
            min_boots_in_one_tail=2, 
            metric=Callable[[np.ndarray, np.ndarray], float])
```

When I run the metric_boot_histogram function, the following error happened.
``` bash
ERROR: test_metric_boot_histogram (tests.unit.test_plot.TestPlotter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mount/arbeitsdaten20/projekte/cik/users/kuan-yu/LSCDBenchmark/tests/unit/test_plot.py", line 93, in test_metric_boot_histogram
    self.P.metric_boot_histogram(self.mock_y_true, self.mock_y_pred)
  File "/mount/arbeitsdaten20/projekte/cik/users/kuan-yu/LSCDBenchmark/./src/plots.py", line 149, in metric_boot_histogram
    [
  File "/mount/arbeitsdaten20/projekte/cik/users/kuan-yu/LSCDBenchmark/./src/plots.py", line 150, in <listcomp>
    self.metric(y_true, y_pred)
  File "/usr/lib64/python3.10/typing.py", line 957, in __call__
    result = self.__origin__(*args, **kwargs)
TypeError: Callable() takes no arguments
```

**Comment by kuan-yu-lin** [comment]
Assign spearmanr from wrappers.
